sample_time_steps: 10
synthetic_data_setup:
  n_customer: 100
  n_category: 303
  n_product: 26176
  category_product_count: [ 881, 604, 421, 408, 379, 335, 313, 310, 310, 308, 307, 301, 300, 289, 283, 274, 258, 258, 252, 251, 246, 242, 241, 231, 229, 227, 222, 216, 214, 212, 210, 210, 201, 199, 194, 194, 189, 188, 187, 186, 184, 180, 178, 171, 168, 165, 163, 154, 153, 150, 148, 148, 147, 145, 135, 135, 133, 132, 132, 129, 127, 126, 120, 116, 114, 114, 113, 113, 113, 113, 112, 112, 112, 112, 112, 110, 107, 107, 107, 105, 105, 103, 102, 101, 100, 100, 100, 98, 97, 97, 97, 97, 96, 95, 95, 94, 93, 93, 93, 93, 92, 92, 90, 90, 89, 88, 87, 87, 86, 84, 84, 84, 83, 82, 81, 80, 80, 79, 79, 79, 78, 76, 76, 76, 76, 75, 75, 74, 74, 73, 71, 71, 70, 69, 66, 64, 64, 63, 63, 63, 63, 62, 62, 62, 61, 60, 60, 60, 59, 59, 58, 58, 58, 58, 57, 57, 56, 55, 55, 54, 53, 53, 53, 52, 51, 50, 50, 50, 49, 49, 49, 48, 47, 47, 47, 46, 46, 46, 45, 45, 45, 44, 44, 43, 43, 42, 41, 41, 40, 39, 38, 38, 38, 38, 37, 37, 37, 37, 37, 36, 36, 36, 36, 36, 35, 34, 34, 34, 33, 33, 33, 33, 32, 31, 29, 28, 28, 26, 25, 25, 25, 24, 24, 24, 23, 23, 23, 23, 22, 22, 21, 21, 20, 20, 20, 20, 20, 19, 19, 19, 18, 18, 18, 17, 17, 17, 17, 16, 15, 14, 14, 14, 14, 14, 14, 12, 12, 12, 11, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 8, 8, 8, 7, 7, 7, 6, 6, 6, 6, 5, 5, 5, 5, 4, 4, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
  store_util_marketing_feature_mode: "random"
  random_seed: 0
  random_seed_range: 100
  # coefficients to generate discount
  discount_depth_distribution:
    _target_: numpyro.distributions.Beta
    concentration1: 15 # alpha, as in the beta distribution
    concentration0: 35 # beta, as in the beta distribution
  discount_state_a_01:
    _target_: numpyro.distributions.Beta
    concentration0: 5
    concentration1: 1
  discount_state_a_11:
    _target_: numpyro.distributions.Beta
    concentration0: 5
    concentration1: 2
  # coefficients to compute product price
  price_alpha_i0:
    _target_: numpyro.distributions.TruncatedNormal
    loc: 1.3
    scale: 0.5
    low: 0
  price_alpha_1:
    _target_: numpyro.distributions.LogNormal
    loc: 0.8
    scale: 1.2
  lowest_price: 0.01

  # coefficients to compute product utility
  utility_beta_ui_z:
    _target_: numpyro.distributions.LogNormal
    loc: 1
    scale: 0.4
  utility_beta_ui_x:
    _target_: numpyro.distributions.LogNormal
    loc: -1
    scale: 1
  utility_beta_i_w:
    _target_: numpyro.distributions.TruncatedNormal
    loc: -3
    scale: 1
    high: 0
  utility_c: -1.4
  utility_beta_u_w:
    _target_: numpyro.distributions.TruncatedNormal
    loc: -3
    scale: 0.8
    high: 0
  utility_clip_percentile: 100
  utility_error_distribution:
    _target_: numpyro.distributions.Gumbel
    loc: 0
    scale: 0.1
  
  # coefficients to compute category utility
  category_choice_gamma_0j_cate:
    _target_: numpyro.distributions.Normal
    loc: -5
    scale: 0.5
  category_choice_gamma_1j_cate:
    _target_: numpyro.distributions.TruncatedNormal
    loc: 0.1
    scale: 0.04
    low: 0
    high: 0.12
  
  # coefficients to compute store visit probability
  store_visit_theta_u:
    _target_: numpyro.distributions.Uniform
    low: 0.25
    high: 0.45
  store_visit_gamma_0_store:
    _target_: numpyro.distributions.Gumbel
    loc: 0
    scale: 0.1
  store_visit_gamma_1_store:
    _target_: numpyro.distributions.TruncatedNormal
    loc: 0.01
    scale: 0.01
    low: 0
  store_visit_gamma_2_store:
    _target_: numpyro.distributions.Uniform
    low: 0.2
    high: 0.3

  # coefficients to compute product demand
  purchase_quantity_gamma_0i_prod:
    _target_: numpyro.distributions.Gumbel
    loc: -2
    scale: 0.1
  purchase_quantity_gamma_1i_prod:
    _target_: numpyro.distributions.LogNormal
    loc: -4
    scale: 0.05
    
